package com.fusionx.lending.product.enums;

public enum ApproveStatus {
	PENDING,
	PENDING_UPDATE,
	APPROVED,
	FRESH,
	CANCELLED,
	PENDING_BLOCK,
	APPROVED_BLOCK,
	BLOCK_REJECTED,
	REJECTED,
	PENDING_REVERSED,
	APPROVED_REVERSE,
	PENDING_BLACKLIST,
	APPROVED_BLACKLIST,
	BLACKLIST_REJECTED,
	BLACKLISTED
}
