package com.fusionx.lending.product.enums;

public enum ServicePoint {

	LEGAL_OFFICER_CONTRACT_ASSIGN,
	LEGAL_CONTRACT_ACCEPT,
	LEGAL_CONTRACT_REJECT,
	
	EXTERNAL_CRIB,
	EXTERNAL_CRIB_RELATION,
	
	EXPENCE_TYPE_CULTIVATION_CATEGORY,

	FACILITY, PRODUCT_PRODUCT_CATEGORY, EXPENCE_TYPE_HOUSEHOLD_EXPENSE_CATEGORY,

	
	BUSINESS_INCOME_EXPENSE,
	CREDIT_APP_COLLLATERAL_DETAILS,
	APPROVAL_CAT_MAP_WITH_PRODUCT,
	GUARANTOR_EXTERNAL_CRIB,

	IDENTIFICATION, CONTACT, 
	ADDRESS,

	
	GUARANTOR_INCOME_EXPENSE,
	GUARANTOR_OTHER_INCOME,CUSTOMER_SALARY_INCOME,CUSTOMER_OTHER_INCOME,CUSTOMER_FINANCIAL_COMMITMENT,GUARANTOR_SALARY_INCOME,GUARANTOR_CULTIVATION_INCOME,DISBURSEMENT_DETAILS,ADDITIONAL_DOCUMENT,

	


	INCOME_EXPENSE_DETAILS,
	INCOME_EXPENSE_TAX,
	CUSTOMER_CUTIVATION_EXPENSE,
	CREDIT_APP_COLL_DOC_DETAILS,
	COL_VALUATION_DETAILS,
	COL_INSURANCE_DETAILS,
	REL_EXTERNAL_CRIB,
	NEW_FACILITY, 
	NEW_FACILITY_CONT,

	CUSTOMER,
	OTHER_DETAILS,

	
	BUSINESS_INCOME_EXPENSES,
	GUARANTOR,
	LINKED_PERSON,
	LEAD_INFOR,
	EXPENCE_TYPE_OTHER_INCOME_CATEGORY,
	ANALYST_EXCEPTION_DETAILS,
	OTHER_INCOME_DETAILS,
	SALARY_INCOME_DETAILS,
	SALARY_INCOME_DOCUMENTS,
	BUSINESS_ADDITIONAL_DETAILS,
	BUSINESS_DOCUMENT_DETAILS,
	BUSINESS_RISK_DETAILS,
	BUSINESS_ASSET_DETAILS,
	BUSINESS_EMPLOYMENT_DETAILS,
	BUSINESS_CLEARANCE_DETAILS,
	CULTIVATION_INCOME_DETAILS,
	CULTIVATION_INCOME_DOCUMENTS,
	BUSINESS_INCOME_DETAILS,
	BUSINESS_INCOME_DOCUMENTS,
	BUSINESS_INCOME_EXPENSE_TYPES,
	BUSINESS_TAX_DETAILS,
	DOCUMENT_CHECKLIST,
	BUSINESS_CENTER
	

}
