package com.fusionx.lending.product.enums;

public enum WorkflowType {
	FEE_CHARGE_TEMP_APPROVAL,
	MASTER_DEFINITION_TEMP_APPROVAL,
	ELIGI_TEMP_APPROVAL,
	INTEREST_TEMP_APPROVAL, REPAYMENT_TEMP_APPROVAL,
	FEE_CHARGE_CAP_TEMP_APPROVAL,
	FEATURE_BENEFIT_TEMP_APPROVAL,CREDIT_APPRAISAL,
}
