package com.fusionx.lending.origination.enums;

public enum CommonListReferenceCode {

	CREDIT_FACILIT_YTYPE,
	FACILITYREASON,
	CRIB_FACILITY_TYPES,
	CRIB_REASONS,
	BORROWER_TYPE, ADDRESSTYPE,
	RELATIONSHIPTYPE,
	TITLE,
	GENDER,
	PERSON,
	CHECKLIST_APP_LEVEL,
	PPERSON,
	CRIB_STATUS, 
	APPROVAL_VARIABLES, 
	EMPLOYMENTCATEGORY,
	OWNERSHIP,
	BUSINESS_SIZE,
	ASSET_TYPE,
	ASSET_OWNERSHIP,
	CLEARENCE_TYPE,
	CLARENCE_AUTHORITY,
	CECKLISTCATEGORY,
	ORGANIZATIONTYPE,
	GUARANTORTYPE,
	STMT_ACC_TYPES,
	CHECKLISTCATEGORY
}
