package com.fusionx.lending.origination.enums;

public enum SuppliesType {
	SUPPLIER,
	LAWYER,
	BUYER,
	ZIZER,
	VALUATION_AGENT,
	INSPECTION_AGENT,
	DEALER,
	AUCTIONEER,
	STOCK_BROKERS,
	LISTED_COMPANIES,
	REGISTRATION_AUTHORITY,
	SECURITY_FIRM,
	YARD_SUPPLIER,
	EMPLOYEE,
	GUARANTOR
}
