package com.fusionx.lending.origination.enums;

public enum TableNamesEnum {
	
	RISK_TEMPLATE,
	RISK_TEMPLATE_DETAIL,
	RISK_PARA_TEMP_CAL_FIELD,
	RISK_PARAMETER_TEMPLATE,
	RISK_TEMPLATE_DETAIL_VARIENCE,
	VAL_PAIR_DETAIL,
	RISK_TEMPLATE_DETAIL_VAL_PAIR,
	FIELD_SET_UP

}
