package com.fusionx.lending.origination.enums;

public enum WorkflowType {
	CREATE,
	UPDATE,
	RULE,
	SUPPLIER_BLACKLIST_APPROVE,
	SUPPLIER_BLACKLIST_REVERT_APPROVE,
	NIC,
	LOAN_CHECK_LIST_TEMPLATE,
	BLACK_LIST_APPROVE ,
	EXTERNAL_CRIB_CHECK,
	REL_EXTERNAL_CRIB_CHECK,
	RELATION_EXTERNAL_CRIB_CHECK,
	GUARANTOR_EXTERNAL_CRIB_CHECK,
	FINAL_APPROVAL,
	ANALYST_EXCEPTION
}
