package com.fusionx.lending.transaction.enums;

public enum BalanceType {
    CLOSINGAVAILABLE,
    CLOSINGBOOKED,
    CLOSINGCLEARED,
    EXPECTED,
    FORWARDAVAILABLE,
    INFORMATION,
    INTERIMAVAILABLE,
    INTERIMBOOKED,
    INTERIMCLEARED,
    OPENINGAVAILABLE,
    OPENINGBOOKED,
    OPENINGCLEARED,
    PREVIOUSLYCLOSEDBOOKED
}
