databaseChangeLog:
  - changeSet:
      id: 1
      author: Venuki
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: brand_id
                  type: bigint
                  constraints:
                    nullable: false
                    foreignKeyName: fk_product_brand_id
                    references: brand(id)
              - column:
                  name: product_group_id
                  type: bigint
                  constraints:
                    nullable: false
                    foreignKeyName: fk_prd_product_group
                    references: product_group(id)                                                         
              - column:
                  name: product_name
                  type: varchar(350)
                  constraints:
                    nullable: false
              - column:
                  name: product_code
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(2500)
                  constraints:
                    nullable: true                     
              - column:
                  name: tenant_id
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: varchar(20)
                  constraints:
                    nullable: false
              - column:
                  name: created_user
                  type: varchar(20)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: modified_user
                  type: varchar(20)
                  constraints:
                    nullable: true
              - column:
                  name: modified_date
                  type: timestamp
                  constraints:
                    nullable: true
              - column:
                  name: version
                  type: bigint
                  defaultValue : 0
                  constraints:
                    nullable: false 
              - column:
                  name: sync_ts
                  type: timestamp
                  defaultValueComputed : current_timestamp          
                  constraints:
                    nullable: false

  - changeSet:
      id: 2
      author: Venuki
      changes:
        - createTable:
            tableName: product_his
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: brand_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: product_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: product_group_id
                  type: bigint
                  constraints:
                    nullable: false                                                        
              - column:
                  name: product_name
                  type: varchar(350)
                  constraints:
                    nullable: false
              - column:
                  name: product_code
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(2500)
                  constraints:
                    nullable: true                    
              - column:
                  name: tenant_id
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: varchar(20)
                  constraints:
                    nullable: false
              - column:
                  name: created_user
                  type: varchar(20)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: modified_user
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: modified_date
                  type: timestamp
                  constraints:
                    nullable: true
              - column:
                  name: history_created_user
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: history_created_date
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: version
                  type: bigint
                  defaultValue : 0
                  constraints:
                    nullable: false
              - column:
                  name: sync_ts
                  type: timestamp
                  defaultValueComputed : current_timestamp          
                  constraints:
                    nullable: false

 
   
       